version: "3"
services:
  joeburgess:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: joeburgess
    environment:
      - BREEZE_API_KEY=${BREEZE_API_KEY}
      - BREEZE_API_URL=http://breeze:8080
    volumes:
      - ./static:/app/static
    ports:
      - "8081:8080"
    networks:
      - joeburgess-network

networks:
  joeburgess-network:
    name: joeburgess-network
    external: true
