version: "3"
services:
  joeburgess-site:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./static:/app/static
    ports:
      - "8081:8080"
    networks:
      - joeburgess-network

networks:
  joeburgess-network:
    driver: bridge
